---

- name: Create Arista VLAN's
  hosts:  arista

  tasks:
    - name: create three VLAN's
      eos_vlan: name={{ item.vlan_name }} vlanid={{ item.vlan_id }}
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

      with_items:
        - {vlan_name: BLUE, vlan_id: 600}
        - {vlan_name: RED, vlan_id: 700}
        - {vlan_name: GREEN, vlan_id: 800}


