---

- name: Update Primary Interface - Ethernet7
  hosts:  arista

  tasks:
#    - name: update interface description
#      eos_interface: name=Ethernet7 description="*** IN USE ***"
#            username={{ eapi_username }}
#            password={{ eapi_password }}
#            host={{ eapi_hostname }}
#            port={{ eapi_port }}
#            transport=https

    - name: update switchport mode
      eos_switchport: name=Ethernet7 mode=trunk trunk_native_vlan=VLAN1 trunk_allowed_vlans=600,700,800
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https


