---

- name: Update Primary Interface - Ethernet7
  hosts:  arista

  tasks:
    - name: update interface description
      eos_interface: name=Ethernet7 description=""
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: update switchport mode
      eos_switchport: name=Ethernet7 mode=access access_vlan=1 trunk_native_vlan=1 trunk_allowed_vlans=1-4094
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: remove VLAN's
      eos_vlan: name={{ item.vlan_name }} vlanid={{ item.vlan_id }} state=absent
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

      with_items:
        - {vlan_name: BLUE, vlan_id: 600}
        - {vlan_name: RED, vlan_id: 700}
        - {vlan_name: GREEN, vlan_id: 800}

