---

- name: Copy file to Cisco Router
  hosts:  pynet-rtr1

  tasks:
    - name: copy file to pynet-rtr1
      cisco_file_transfer: 
            source_file="/home/cdieken/python_class/class6/ANSIBLE/cisco_logging.txt"
            dest_file=cisco_logging8.txt
            overwrite=true
            enable_scp=true
            username={{ username }}
            password={{ password }}
            host={{ host }}
            port={{ port }}

