---
- name: Generate configuration file
  template: src=router1_forloop2.j2 dest=/home/cdieken/python_class/class5/{{item.hostname}}.txt
  with_items:
      - {hostname: pynet-rtr1, ip_addr: 1.1.1.1}
      - {hostname: pynet-rtr2, ip_addr: 1.1.1.2}
      - {hostname: pynet-rtr3, ip_addr: 1.1.1.3}

