---
- hosts: local
  vars:
    hostname: pynet-rtr1
  tasks:
    - name: Generate configuration file
      template: src=/home/cdieken/python_class/class5/router1.j2
                  dest=/home/cdieken/python_class/class5/router1.txt



