---
- hosts: local
  tasks:
    - name: Generate configuration file
      template: src=/home/cdieken/python_class/class5/router1_forloop.j2
                  dest=/home/cdieken/python_class/class5/{{item.hostname}}.txt
      with_items:
        - hostname: pynet-rtr1
        - hostname: pynet-rtr2
        - hostname: pynet-rtr3



